In [2]:
df=pd.read_csv("Churn_Modelling.csv",index_col=0)

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import RobustScaler,OneHotEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix,precision_score,accuracy_score,recall_score,f1_score

In [3]:
df.head()

CustomerId   Surname  CreditScore Geography  Gender  Age  Tenure  \
RowNumber                                                                     
1            15634602  Hargrave          619    France  Female   42       2   
2            15647311      Hill          608     Spain  Female   41       1   
3            15619304      Onio          502    France  Female   42       8   
4            15701354      Boni          699    France  Female   39       1   
5            15737888  Mitchell          850     Spain  Female   43       2   

             Balance  NumOfProducts  HasCrCard  IsActiveMember  \
RowNumber                                                        
1               0.00              1          1               1   
2           83807.86              1          0               1   
3          159660.80              3          1               0   
4               0.00              2          0               0   
5          125510.82              1          1               1   

           EstimatedSalary  Exited  
RowNumber                           
1                101348.88       1  
2                112542.58       0  
3                113931.57       1  
4                 93826.63       0  
5                 79084.10       0

In [4]:
df.drop(columns=['CustomerId','Surname'],inplace=True)

In [5]:
print(df.shape)

(10000, 11)


In [6]:
print(df.isna().sum())

CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64


In [7]:
x=df.drop('Exited',axis=1) 
y=df.Exited

In [8]:
print(y.value_counts())

Exited
0    7963
1    2037
Name: count, dtype: int64


In [9]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0,stratify=y)

In [10]:
print(x.columns)

Index(['CreditScore', 'Geography', 'Gender', 'Age', 'Tenure', 'Balance',
       'NumOfProducts', 'HasCrCard', 'IsActiveMember', 'EstimatedSalary'],
      dtype='object')


In [11]:


num_cols=['CreditScore','Age', 'Tenure', 'Balance','NumOfProducts', 'EstimatedSalary'] 
cat_cols=['Geography','Gender', 'HasCrCard', 'IsActiveMember']

In [13]:
p = Pipeline(steps=[
    ('ct', ColumnTransformer(
        transformers=[
            ('s1', RobustScaler(), num_cols),
            ('s2', OneHotEncoder(sparse_output=False, handle_unknown='ignore'), cat_cols)
        ]
    )),
    ('mod', LogisticRegression(random_state=0))
])


In [14]:
p.fit(x_train,y_train)

Pipeline(steps=[('ct',
                 ColumnTransformer(transformers=[('s1', RobustScaler(),
                                                  ['CreditScore', 'Age',
                                                   'Tenure', 'Balance',
                                                   'NumOfProducts',
                                                   'EstimatedSalary']),
                                                 ('s2',
                                                  OneHotEncoder(handle_unknown='ignore',
                                                                sparse_output=False),
                                                  ['Geography', 'Gender',
                                                   'HasCrCard',
                                                   'IsActiveMember'])])),
                ('mod', LogisticRegression(random_state=0))])

In [15]:
preds=p.predict(x_test)

In [16]:
print(preds[:15])

[1 0 0 1 0 0 0 0 0 0 0 1 0 0 0]


In [17]:
print(confusion_matrix(y_true=y_test,y_pred=preds))

[[1530   63]
 [ 319   88]]


In [18]:
print(confusion_matrix(y_test,preds,labels=(1,0)))

[[  88  319]
 [  63 1530]]


In [19]:
TP,FN,FP,TN=confusion_matrix(y_test,preds,labels=(1,0)).ravel()

In [20]:
print(precision_score(y_test,preds))

0.5827814569536424


In [21]:
print(recall_score(y_test,preds))

0.21621621621621623


In [22]:
print(f1_score(y_test,preds))

0.31541218637992835
